[package]
name = "serde_cbor_map"
version = "0.1.0"
authors = ["Patrick Uiterwijk <patrick@puiterwijk.org>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
#syn = "1.0"
syn = "1.0"
quote = "1.0"
